testing husky with eslint, prettier and now jest tests

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,11 @@
-npx lint-staged
+# Get the list of staged files (only .js, .ts, .tsx, .jsx)
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=AM | grep -E '.(js|ts|tsx|jsx)$')
+
+# Run Jest tests on the related files only
+if [ -n "$STAGED_FILES" ]; then
+  npx jest --bail --findRelatedTests $STAGED_FILES
+  if [ $? -ne 0 ]; then
+    echo "Jest tests failed. Aborting commit."
+    exit 1
+  fi
+fi
